kind: Template
apiVersion: v1
objects:

  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: ${NAME}

  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: nginx
    spec:
      dockerImageRepository: docker.io
      tags:
        - name: latest

  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: ${NAME}
    spec:
      source:
        type: Git
        git:
          uri: https://github.com/kvaidas/nginx-openshift
      strategy:
        type: Docker
        dockerStrategy:
          from:
            kind: DockerImage
            name: 'nginx:latest'
          env:
            - name: NGINX_PORT
              value: "8080"
      output:
        to:
           kind: ImageStreamTag
           name: ${NAME}:latest
      triggers:
        - type: ConfigChange
        - type: ImageChange

  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: ${NAME}
    spec:
      strategy:
        type: Rolling
      replicas: "${{REPLICA_COUNT}}" 
      template:
        spec:
          containers:
          - name: ${NAME}
            readinessProbe:
              timeoutSeconds: 1
              initialDelaySeconds: 5
              httpGet:
                path: /
                port: 8080
        metadata:
          labels:
            name: ${NAME}
      selector:
        name: ${NAME}
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            from:
              kind: ImageStreamTag
              name: ${NAME}:latest
            containerNames:
              - ${NAME}

  - kind: Service
    apiVersion: v1
    metadata:
      name: ${NAME}
    spec:
      ports:
        - port: 80
          targetPort: 8080
      selector:
        name: ${NAME}

  - kind: Route
    apiVersion: v1
    metadata:
      name: ${NAME}
    spec:
      to:
        kind: Service
        name: ${NAME}
        weight: 100

metadata:
  name: project-engine

parameters:
  - name: NAME
    required: true
    generate: expression
    from: "engine-[a-z0-9]{16}"
    description: The name assigned to all objects
  - name: REPLICA_COUNT
    description: Number of replicas to run
    value: "2"
    required: true
